[package]
name = "enigmatik"
version = "0.0.0"
edition = "2021"
authors = ["Alessandro Bartoli <alessandro@bartolilab.it>"]

[[bin]]
name = "enigmatik"
path = "src/main.rs"

[dependencies]
rand = "0.8"

[profile.release]
opt-level = 3
